This is makeindex, version 2.15 [MiKTeX 2.9.6730 64-bit] (kpathsea + Thai support).
Scanning style file ./master_thesis_v5.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file master_thesis_v5.acn....done (326 entries accepted, 0 rejected).
Sorting entries......done (3072 comparisons).
Generating output file master_thesis_v5.acr....done (151 lines written, 0 warnings).
Output written in master_thesis_v5.acr.
Transcript written in master_thesis_v5.alg.
